config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'

  resources :users, only: [:index, :new, :create]
  get 'sessions/new', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'

  get 'chats', to: 'chats#home', as: :chat
  get 'token', to: 'chats#token'
  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user 
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to sessions_new_path
    end
  end

  def not_logged_in_user
  	unless !logged_in?
  		flash[:danger] = "You are already logged in"
      redirect_to users_path
  	end
  end
end

app/controllers/chats_controller.rb
require 'net/http'

class ChatsController < ApplicationController
    before_action :logged_in_user

    def home
        identity = current_user.id
        token = Twilio::Util::AccessToken.new "AC6e8a6ac0cde02b70cf13757258df57fc",
            "SK900b984c5d76c02721eed8bbf2a98fc6",
            "BCOR2EW40sDQQv9N3N5caVNM1tve1ebM", 3600, identity

        local_sid = "IS63900aeb7f6a40478fada67771a95dc9"
        heroku_sid = "IS179e2a15beac4a23aeb19d8bcbfad6ef"

        # Create IP Messaging grant for our token
        grant = Twilio::Util::AccessToken::IpMessagingGrant.new
        grant.service_sid = local_sid
        grant.endpoint_id = "procore_chat:#{identity}:browser"
        token.add_grant grant

        @token = token.to_jwt
        @users = User.all

        cmd = "curl -X POST https://ip-messaging.twilio.com/v1/Services/#{local_sid} \
               -d 'ReachabilityEnabled=true' \
               -u 'AC6e8a6ac0cde02b70cf13757258df57fc:4cd11afae4208bf3beead39b6c23a389'"

        puts cmd

        wasGood = system( cmd )

        puts wasGood

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :not_logged_in_user, only: [:new, :create]

	def new
	end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user 
      log_in user
      redirect_to users_path
    else
      flash.now[:danger] = "Invalid user"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @users = User.all
  end

	def new
		@user = User.new
	end

	def create 
		@user = User.new(user_params)
    if @user.save
      flash[:success] = "User created"
      redirect_to root_url
    else
      render :new
    end
	end

	private

		def user_params
			params.require(:user).permit(:name,
										               :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chats/home.html.erb
<div class="home">
    <%= react_component "ChatAppClient",
	                    props: {
	                      token: @token,
	                      users: @users,
	                      currentUser: current_user
	                    } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>ProcoreChat</title>
      <%= favicon_link_tag 'favicon.ico' %>
      <script src="https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"></script>
      <script src="https://media.twiliocdn.com/sdk/rtc/js/ip-messaging/v0.10/twilio-ip-messaging.min.js"></script>
      <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.orange-deep_orange.min.css" />
      <script src="https://use.fontawesome.com/4ec0e2c6e7.js"></script>
      <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.deep_orange-red.min.css" />
      <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <%= image_tag ("procore-logo1.png"), :size => '50x50', :class => "procore-logo" %>
        <span class="mdl-layout-title">
          <%if logged_in? %>
            <%= "Welcome, #{current_user.name}!" %>
          <% else %>
            ProcoreChat
          <% end %>  
        </span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
        <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <% if logged_in? %>
            <%= link_to "Log Out", sessions_path, method: "delete", class: "btn btn-warning" %>
          <% end %>
        </nav>
      </div>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="page-content"><%= yield %></div>
    </main>
  </body>
</html>

app/views/users/_error_messages.html.erb
<% object.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

app/views/users/index.html.erb
<div class="user-list">
    <%= button_to "Chat", chat_path, :class => "btn btn-primary", method: :get %>
    <br>
    <h3>Users</h3>
    <% @users.each do |user| %>
        <%= user.name %>, <%= user.email %></br>
<% end %>
</div>

app/views/users/new.html.erb
<h1 style="text-align: center">Create New User</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages', object: f.object %>
      <%= f.label :name, class: 'label-text'%>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email, class: 'label-text' %>
      <%= f.email_field :email, class: 'form-control' %>
      <br>
      <%= f.submit "Create User", class: "btn btn-primary center-block" %>
      <%= link_to "Already signed up? Log in!", sessions_new_path, class: 'btn btn-link center-block' %>
    <% end %>
  </div>
</div>